home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^index1$', views.index1, name='index1'),
    url(r'^index$', views.index, name='index'),
    url(r'^page_item$', views.page_item, name='page_item'),
    url(r'^test$', views.test, name='test'),
]

spider/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('home.urls', namespace='home', app_name='home'))
]

home/models.py
# models.py
from django.db import models


class Company(models.Model):
    company_name = models.CharField(max_length=64)

home/views.py
# -*- coding: utf-8 -*-
import sys
from django.http import HttpResponse, Http404
from django.views.generic.list import ListView
from django.shortcuts import render
from django.urls import reverse
import json
import urllib
import urllib2
import re
import requests
from urllib2 import urlparse
import html


# 首页
def index(request):
    return render(request, 'index.html')


def index1(request):
    if request.method == 'GET':
        return render(request, 'index1.html')
    else:
        url_name = request.POST['url_name']
        mydict = {"url_name": url_name}
        return HttpResponse(
            json.dumps(mydict),
            content_type="application/json"
        )

# 显示爬取页面
def page_item(request):
    url_name = request.POST['url_name']
    load_html = requests.get(url_name)
    load_html.encoding = 'utf-8'
    content = load_html.text
    # 标题
    title = re.findall(r'<title>(.*?)</title>', content)
    title = title[0]
    # 头部<head>
    pattern_head = re.compile('<head>.*?</head>', re.S)
    head_content = re.findall(pattern_head, load_html.text)
    head = head_content[0].replace('<head>', '')   # 去掉head
    head = head.replace('</head>', '')
    pattern_head_href = re.compile('href=\"css.*?\"', re.S)   # 匹配没有http的css
    head_href = re.findall(pattern_head_href, head)
    head_href_arr = []
    if head_href != '':
        for h_href in head_href:
            h_href = h_href.replace('href="', '')
            h_href = h_href.replace('"', '')
            head = head .replace(h_href,'')
            head_href_arr.append(h_href)
    pattern_sc_head = re.compile('<script.*?</script>', re.S)
    sc_head = re.findall(pattern_sc_head, head)   # 头部 除了js文件
    src_head_arr1 = []  # 引入的js文件
    src_head_arr2 = []  # js代码
    for s_head in sc_head:
        pattern_src = re.compile('[a-z]+:\/\/[a-zA-Z0-9_\-\/.%]+', re.L)  # 匹配js
        src = re.findall(pattern_src, s_head)
        if len(src) == 1:
            src_head_arr1.append(src[0])  # 保存到一个数组 js文件
        pattern_sc_ = re.compile('<script.*?>', re.S)  # 匹配script开头
        s_ = re.findall(pattern_sc_, s_head)
        s_head_ = s_head.replace(s_[0], '')
        s_head_ = s_head_.replace('</script>', '')
        s_head_ = s_head_.replace('\r\n', '')
        if s_head_ != '':
            src_head_arr2.append(s_head_)  # 保存到一个数组 js代码
        head = head.replace(s_head, '')

    # body
    pattern_body = re.compile('<body.*?</body>', re.S)
    pattern_body1 = re.compile('<body.*?>', re.S)
    body_content = re.findall(pattern_body, load_html.text)
    b = re.findall(pattern_body1, load_html.text)
    body = body_content[0].replace(b[0], '')
    body = body.replace('</body>', '')
    pattern_script1 = re.compile('<script>.*?</script>', re.S)
    script1 = re.findall(pattern_script1, body)
    for sc1 in script1:
        body = body.replace(sc1, '')
    pattern_script2 = re.compile('<script.*?</script>', re.S)
    script2 = re.findall(pattern_script2, body)
    for sc2 in script2:
        body = body.replace(sc2, '')
    # 所有<body>里面的元素
    element = re.findall(r'<([a-z]+)', body)
    element_arr = []
    for e in element:
        element_arr.append(e)

    # 根据元素获取里面所有所有的class及对应的链接
    con = re.findall(r'<(.*?)>', body)
    classes_arr = []
    urls_arr = []
    for co in con:
        classes = re.findall(r'class="(.*?)"', co)
        if len(classes) != 0:
            classes_arr.append(classes[0])
        else:
            classes_arr.append('')
        url = re.findall(r'([a-z]+:\/\/[a-zA-Z0-9_\-\/.%]+)', co)
        if len(url) != 0:
            urls_arr.append(url[0])
        else:
            urls_arr.append('')

    dic = {"url": url_name, "title_name": title, "head": head, "head_href": head_href_arr, "src_head1": src_head_arr1,
           "src_head2": src_head_arr2, "body": body,"element":element_arr,"classes": classes_arr,"urls":urls_arr}
    return render(request, 'page_item.html', {'dic':json.dumps(dic)})
    # return render(request, 'page_item.html', dic)




def test(request):
    url_name = request.POST['url_name']
    # print url_name
    # exit()
    dic = {"url_name": url_name}
    return render(request, 'test.html', dic)

# 首页视图,继承自ListVIew
class IndexView(ListView):
    # template_name属性用于指定使用哪个模板进行渲染
    template_name = "home/index1.html"
    # context_object_name属性用于给上下文变量取名（在模板中使用该名字）
    context_object_name = "home_index"

home/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>智能爬虫</title>
     <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

</head>
<style>
    body{background-color: #162F42}
    a{text-decoration:none;}
    .main{width: 960px;height: 100%;margin-left:auto;margin-right:auto;}
    .head{margin-top: 16px}
    .logo{float: left}
    .logo h2{color: #ffffff}
    .login{float: right;padding-top: 32px}
    .login a{color: #ffffff;font-weight: bold}
    .line{clear: both;opacity: 1;width: 960px;margin: 0 auto;height: 1px;background-color: #ffffff;background: rgba(255,255,255,.3);transition: width .2s ease-in-out;}
    .title{margin-top: 40px;margin-bottom: 40px;text-align: center}
    .title span{color: #ffffff;font-weight: bold;font-size: 40px}
    .input{padding-top: 40px;padding-bottom: 40px;text-align: center}
    .url_input{font-size: 18px;width: 500px;height: 40px;padding-left:16px;border-radius: 5px;border: none;outline: 0;margin-right: 20px;font-weight: 300;}
    .btn{height: 40px;font-size: 14px}

    .foot{position:absolute;bottom:0;height: 100px;text-align: center}
    .footer{margin-top: 40px}
    .footer p{color: #ffffff;font-size: 12px}
</style>
<body>
    <div class="main">
        <div class="head">
            <div class="logo"><h2>杭州数立方征信有限公司</h2></div>
            <div class="login">
                <a href="#">登录</a>
                <a href="#">注册</a>
            </div>
        </div>
        <div class="line"></div>
        <div class="title"><span>新一代智能爬虫</span></div>
        <form id="spider_from" action="{% url 'home:page_item' %}" method="post">
            {% csrf_token %}
            <div class="input">
                <input id="url_name" class="url_input" type="text" name="url_name" placeholder="输入数据来源网址"/>
                <button id="spider_submit" type="submit" class="btn btn-default" >开始爬取</button>
            </div>
        </form>

        {#  底部  #}
        <div class="foot">
            <div class="line"></div>
            <div class="footer">
                <p> Copyright 2017 HANGZHOU DATA CUBE CREDIT REFERENCE CO.,LTD All Rights Reserved</p>
            </div>
        </div>
    </div>


    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'layer/layer.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#spider_submit').click(function () {
                var url = $('#url_name').val();
                 if(!check_url(url)){
                    layer.msg('请输入正确数据来源网址！');
                    return false;
                 }
{#                 $.ajax({#}
{#                     url:"/index",#}
{#                     data:$('#spider_from').serialize(),#}
{#                     type:'post',#}
{#                     success:function (data) {#}
{#                         var url_name = data['url_name'];#}
{#                         alert(url_name);#}
{#                         location.href = "{% url 'home:page_item' %}";#}
{#                         location.href = "/page_item/"+url_name;#}
{#                         layer.msg(data['url_name'])#}
{#                         console.log(data['url_name']);#}
{#                     }#}
{#                 });#}
            });
        });
        //判断是不是合法网站
        function check_url(url) {
            if((/^((https|http|ftp|rtsp|mms)?:\/\/)[^\s]+/.test(url))){
                return 1;
            }
             return 0;
        }
    </script>
</body>
</html>

home/templates/index1.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>爬虫</title>
     <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

</head>
<style>
    body{background-color: #162F42}
    a{text-decoration:none;}
    .main{width: 960px;height: 100%;margin-left:auto;margin-right:auto;}
    .head{margin-top: 16px}
    .logo{float: left}
    .logo h2{color: #ffffff}
    .login{float: right;padding-top: 32px}
    .login a{color: #ffffff;font-weight: bold}
    .line{clear: both;opacity: 1;width: 960px;margin: 0 auto;height: 1px;background-color: #ffffff;background: rgba(255,255,255,.3);transition: width .2s ease-in-out;}
    .title{margin-top: 40px;margin-bottom: 40px;text-align: center}
    .title span{color: #ffffff;font-weight: bold;font-size: 40px}
    .input{padding-top: 40px;padding-bottom: 40px;text-align: center}
    .url_input{font-size: 18px;width: 400px;height: 40px;border-radius: 5px;border: none;outline: 0;margin-right: 20px;font-weight: 300;}
    .url_addr{font-size: 14px;width: 300px;height: 40px;border-radius: 5px;border: none;outline: 0;font-size: 14px;padding-left: 12px;margin-right: 20px}
    .url_addr option{font-size: 14px}
    .btn{height: 40px;font-size: 14px}

    .foot{position:absolute;bottom:0;height: 100px;text-align: center}
    .footer{margin-top: 40px}
    .footer p{color: #ffffff;font-size: 12px}
</style>
<body>
    <div class="main">
        <div class="head">
            <div class="logo"><h2>杭州数立方征信有限公司</h2></div>
            <div class="login">
                <a href="#">登录</a>
                <a href="#">注册</a>
            </div>
        </div>
        <div class="line"></div>
        <div class="title"><span>新一代智能爬虫</span></div>
        <form id="spider_from" action="" method="post">
            {% csrf_token %}
            <div class="input">
                <input id="url_name" class="url_input" type="text" name="url_name" placeholder="请输入企业名称"/>
                <select id="url_addr" class="url_addr" name="url_addr">
                    <option value ="">请选择网站</option>
                    <option value ="1">建设通</option>
                    <option value="2">四库一平台</option>
                    <option value="3">水滴信用</option>
                    <option value="4">浙江省建筑市场监管与诚信信息平台</option>
                </select>
                <button id="spider_submit" type="button" class="btn btn-default" >开始爬取</button>
            </div>
        </form>

        {#  底部  #}
        <div class="foot">
            <div class="line"></div>
            <div class="footer">
                <p> Copyright 2017 HANGZHOU DATA CUBE CREDIT REFERENCE CO.,LTD All Rights Reserved</p>
            </div>
        </div>
    </div>


    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'layer/layer.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#spider_submit').click(function () {

                 if(!$('#url_name').val()){
                    layer.msg('企业名称不能为空！');
                    return false;
                 }
                 if(!$('#url_addr').val()){
                    layer.msg('爬取网址不能为空！');
                    return false;
                 }
                 $.ajax({
                     url:"/index",
                     data:$('#spider_from').serialize(),
                     type:'POST',
                     success:function (data) {
                         layer.msg(data['url_name'])
                     }
                 });
            });
        });
    </script>
</body>
</html>

home/templates/page_item.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>智能爬虫</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
</head>
<style>
    body{margin: 0;padding: 0;overflow: hidden;background-color: #F1F1F1;color: #717171;}
    a{text-decoration:none;}
    .main{position: absolute;verflow-y: scroll;height: 100%;width: 100%}
    .top{position: fixed;z-index: 999;width: 100%;background: #162F42;color: #f7f7f7;text-align: center;height: 80px;overflow: hidden;margin-top: 0;font-size: 16px;}
    .back{float: left; width: 120px;border: 1px solid;border-radius: 50px;margin: 20px;position: fixed;z-index: 100;height: 40px;line-height: 40px;cursor: pointer}
    .title{position: absolute;top: 15px;left: 0;width: 100%;display: inline-block;}
    .crawl_title{width: 60%;margin: 0 auto;overflow: hidden;white-space: nowrap;text-overflow: ellipsis;}
    .rule{cursor: pointer;width: 50%;display: inline-block;margin: 5px;color: rgba(255,255,255,.8);font-size: 12px;}
    .load_page{margin-top:80px;padding:0;height:100%;width:100%;}
    .next{position: relative;float: right;width: 120px;border: 1px solid;border-radius: 50px;margin: 20px;height: 40px;line-height: 40px;cursor: pointer;}

    .bottom{position:absolute;width:100%;bottom:0;height: 200px;background-color: #162F42;color: #F1F1F1;overflow-y: scroll}
    .head_line{margin-top: 20px;margin-left: 20px;font-size: 16px;}
    .line{opacity: 1;margin-top: 20px;height: 1px;background-color: #F1F1F1;transition: width .2s ease-in-out;}
    .crawl_table{margin: 0;font-size: 14px;}
    .thead{width: 300px;height: 30px;border-bottom: solid 1px #F1F1F1;border-right: solid 1px #F1F1F1;}
    .tr{margin-left: 20px;line-height: 30px}
    .tbody{width: 300px;height: 30px;border-bottom: solid 1px #F1F1F1;border-right: solid 1px #F1F1F1;}
    .td{margin-left: 20px;line-height: 30px}
    .hover{background-color: #5cb85c}
</style>
<body>
    <div class="main">
        <div class="top">
            <div class="back">返回</div>
            <div class="title">
{#                <div class="crawl_title">正在爬取：{{ title_name }}</div>#}
                <div class="crawl_title" id="crawl_title">正在爬取：</div>
                <div class="rule">查看使用说明</div>
            </div>

            <div class="next" id="next">
                完成创建
            </div>
        </div>
{#        <textarea style="display: none" id="html_nome">{{ html|safe }}</textarea>#}
{#        <iframe class="load_page" id="load_page" src="{{ url|safe }}"></iframe>#}
        <iframe class="load_page" id="load_page" src=""></iframe>

        <!--底部弹出对话框-->
        <div class="bottom">
            <div class="head_line">点击页面元素来选取数据，数据预览将会显示在这里</div>
            <div class="line"></div>
            <div class="crawl_table">
                <div class="thead">
                    <div class="tr">列表一</div>
                </div>
                <div class="tbody">
                    <div class="td"></div>
                </div>
            </div>
        </div>
    </div>


    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
{#    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>#}
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'layer/layer.js' %}"></script>
    <script type="text/javascript">

        $(function () {
            var m = {{ dic|safe }}
            $('#crawl_title').append(m['title_name'])
            for(var i = 0;i<m['src_head1'].length;i++){
                var script_head1 = "<script type=\"text/javascript\"  src=\"" +m ['src_head1'][i] + "\"><\/script>"
{#                 $("iframe").contents().find('head').append(script_head1)#}
{#                console.log(script_head1);#}
            }
            //添加css
            for(var i = 0;i<m['head_href'].length;i++){
                var href = "<link rel=\"stylesheet\" href=\"" + m['url'] + m ['head_href'][i] + "\"\/>"
                 $("iframe").contents().find('head').append(href);
                console.log(href);
            }
            //添加头部
            $("iframe").contents().find('head').append(m['head']);
            //添加选中了高亮显示
            var st = $("iframe").contents().find('style');
            if(st.length == 0){
                var h1 = "<style>.hover{background: #5cb85c;}<\/style>"
                $("iframe").contents().find('head').append(h1);
            }else {
                var h2 = ".hover{background: #5cb85c;}"
                $("iframe").contents().find('style').append(h2);
            }
{#            console.log(st.length);#}


            for(var j = 0;j<m['src_head2'].length;j++){
                var script_head2 = "<script >" + m ['src_head2'][j] + "<\/script>";
{#                 $("iframe").contents().find('head').append(script_head2)#}
{#                console.log(script_head2);#}
            }

            $("iframe").contents().find('body').append(m['body']);
            console.log(m['url']);
            // 去掉<a>标签的href和点击事件
            $("iframe").contents().find('a').removeAttr('href');
            $("iframe").contents().find('a').removeAttr('onclick');

            //给所有的表现添加cursor 及一个伪id 添加划入划出效果
            var sum_wid = 0;
            for(var i = 0;i<m['element'].length;i++){
                var el = m['element'][i];
                $("iframe").contents().find(el).css('cursor','pointer');
                $("iframe").contents().find(el).attr('wid',i);
                $("iframe").contents().find(el).hover(
                    function () {
                        $(this).parents().removeClass('hover')
                        $(this).addClass("hover");
                    },
                    function () {
                        $(this).removeClass("hover");
                    }
                );
                sum_wid = i;
{#                console.log(m['element'][i]);#}
            }
            //获取选择的值
            for(var i = 0;i<m['classes'].length;i++){
                var classes = m['classes'][i];
                if(classes != ''){
                    class_arr = classes.split(' ');
                    var cl = '';
                    for(var j = 0;j<class_arr.length;j++){
                        if(class_arr[j] != ''){
                            cl =cl + '.' + class_arr[j];
                        }
                    }
                    // 点击区域
                    $("iframe").contents().find(cl).click(function () {
                        var click_class = $(this).attr('class');
                        click_arr = click_class.split(' ');
                         var cli = '';
                        for(var k = 0;k<click_arr.length-1;k++){
                            if(click_arr[k] != ''){
                                cli =cli + '.' + click_arr[k];
                            }
                        }
{#                        console.log(cli);#}
                        var str_arr = [];//保存数组
                        $("iframe").contents().find(cli).each(function () {
                            var t = $(this).text();
                            str_arr.push(t);

                        });

{#                        for(var k = 0;k < str_arr){}#}
                        for(var k = 0;k<str_arr.length;k++){
                            $('.td').html(str_arr[0]);
                        }
{#                        console.log(str_arr[0]);#}
                        return false;
                    });
                }
            }
{#            console.log(str_arr);#}
            //
            var n = 0;
            $("iframe").contents().find('.jy_blue1.span1 ').each(function () {
                 var s = $(this).text();
{#                 console.log(s);#}
            });

        })

    </script>

</body>
</html>

home/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ url_name }}
</body>
</html>